# fly.toml app configuration file generated for codecaptain on 2023-06-30T07:59:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codecaptain"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  app = "overmind start"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "codecaptain_data"
  destination = "/app/data"
